version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "coatesTest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-t9b8h373cfk7"
s3_prefix = "coatesTest"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

